import type { LiveShowEntryProps } from "~/components/live-show-entry/live-show-entry";

export type LiveShow = LiveShowEntryProps;

export const LIVE_SHOWS: LiveShow[] = [
  {
    country: "Italy",
    city: "Palermo",
    host: "Mind House",
    venue: "Mind House",
    date: "2024-11-30",
  },
  {
    country: "Italy",
    city: "Bologna",
    host: "Freakout Club",
    venue: "Freakout Club",
    date: "2024-10-13",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "Malotempo Fest Ed. I",
    date: "2024-07-19",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Palestra L.U.Po.",
    venue: "Necrosis Fest Ed. II",
    date: "2024-05-11",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2024-05-03",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2024-04-26",
    cancelled: true,
  },
  {
    country: "Italy",
    city: "Torretta",
    host: "Torrettacore",
    venue: "Torrettacore",
    date: "2024-04-01",
  },
  {
    country: "Italy",
    city: "Reggio Calabria",
    host: "Interzone",
    venue: "Interzone",
    date: "2024-03-23",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Baraccio",
    venue: "Baraccio",
    date: "2024-03-22",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Centro sociale Anomalia",
    venue: "Centro sociale Anomalia",
    date: "2024-02-16",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    date: "2023-12-09",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Roxanne",
    venue: "Roxanne",
    date: "2023-10-27",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "Punk Festival",
    date: "2023-10-06",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Palestra L.U.Po.",
    venue: "Palestra L.U.Po.",
    date: "2023-09-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExMusik Fest Ed. II",
    date: "2023-07-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2023-04-28",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2023-03-10",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    date: "2023-03-09",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Nuove Officine Zisa",
    venue: "Nuove Officine Zisa",
    date: "2023-01-05",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    date: "2022-10-27",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    date: "2022-09-17",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2022-07-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Palermo Festival",
    venue: "Renzo Barbera",
    date: "2022-06-18",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    date: "2022-06-11",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "P.Y.C.",
    venue: "P.Y.C.",
    date: "2022-06-03",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    date: "2022-05-31",
  },
];
