import type { LiveShowEntryProps } from "~/components/live-show-entry/live-show-entry";

export type LiveShow = LiveShowEntryProps;

export const LIVE_SHOWS: LiveShow[] = [
  {
    country: "Italy",
    city: "Palermo",
    host: "E.P.Y.C.",
    venue: "E.P.Y.C.",
    with: ["Komarov Magnificent Backflip"],
    date: "2026-03-20",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "E.P.Y.C.",
    venue: "Malotempo x E.P.Y.C.",
    with: ["Mother Giraffe", "Your Noisy Neighbors"],
    date: "2025-11-08",
  },
  {
    country: "Italy",
    city: "Cinisi",
    host: "Bunkerino",
    venue: "Bunkerino",
    with: ["others"],
    date: "2025-11-02",
  },
  {
    country: "Italy",
    city: "Cinisi",
    host: "Pool F*cking Party",
    venue: "Pool F*cking Party",
    with: ["Mostardacida", "Descuncumiddatus", "Negative Path", "others"],
    date: "2025-08-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Centro Sociale Anomalia",
    venue: "Centro Sociale Anomalia",
    with: ["Descuncumiddatus", "others"],
    date: "2025-05-09",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Mind House",
    venue: "Mind House",
    with: ["Rhino", "Space Travel", "others"],
    date: "2024-11-30",
  },
  {
    country: "Italy",
    city: "Bologna",
    host: "Freakout Club",
    venue: "Freakout Club",
    with: ["Nadsat", "Grufus"],
    date: "2024-10-13",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "Malotempo Fest Ed. I",
    with: ["Stormo", "Komarov Magnificent Backflip", "Nadsat", "others"],
    date: "2024-07-19",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Palestra L.U.Po.",
    venue: "Necrosis Fest Ed. II",
    with: ["Descuncumiddatus", "Sumptus", "Nihil"],
    date: "2024-05-11",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    with: ["Not Another Prayer"],
    date: "2024-05-03",
  },
  {
    country: "Italy",
    city: "Torretta",
    host: "Torrettacore",
    venue: "Torrettacore",
    with: ["Mostardacida", "Mosquitos Like Helicopters", "others"],
    date: "2024-04-01",
  },
  {
    country: "Italy",
    city: "Reggio Calabria",
    host: "Interzone",
    venue: "Interzone",
    date: "2024-03-23",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Baraccio",
    venue: "Baraccio",
    date: "2024-03-22",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Centro sociale Anomalia",
    venue: "Centro sociale Anomalia",
    with: ["Consumer", "Nadsat"],
    date: "2024-02-16",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    with: ["Grymalin", "Descuncumiddatus"],
    date: "2023-12-09",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Roxanne",
    venue: "Roxanne",
    date: "2023-10-27",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "Punk Festival",
    with: ["Mostardacida", "others"],
    date: "2023-10-06",
  },
  {
    country: "Italy",
    city: "Catania",
    host: "Palestra L.U.Po.",
    venue: "Palestra L.U.Po.",
    with: ["Carcano", "Mother Giraffe", "Gigantik"],
    date: "2023-09-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExMusik Fest Ed. II",
    with: ["Luglio 1984", "Not Another Prayer"],
    date: "2023-07-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    with: ["Smokeden"],
    date: "2023-04-28",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    with: ["Luglio 1984"],
    date: "2023-03-10",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    with: ["Mostardacida", "others"],
    date: "2023-03-09",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Nuove Officine Zisa",
    venue: "Nuove Officine Zisa",
    with: ["Nurturance"],
    date: "2023-01-05",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    date: "2022-10-27",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    date: "2022-09-17",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "ExKarcere",
    venue: "ExKarcere",
    date: "2022-07-30",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Palermo Festival",
    venue: "Renzo Barbera",
    date: "2022-06-18",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "Alibi",
    venue: "Alibi",
    date: "2022-06-11",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "P.Y.C.",
    venue: "P.Y.C.",
    date: "2022-06-03",
  },
  {
    country: "Italy",
    city: "Palermo",
    host: "UniPA",
    venue: "UniPA",
    date: "2022-05-31",
  },
];
